# Generated by Django 2.1.4 on 2020-04-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links_small',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(blank=True, max_length=20)),
                ('imdbId', models.CharField(blank=True, max_length=20)),
                ('tmdbId', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
