# Generated by Django 2.1.4 on 2020-04-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0002_links_small'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.CharField(blank=True, max_length=20)),
                ('belongs_to_collection', models.CharField(blank=True, max_length=2000)),
                ('budget', models.CharField(blank=True, max_length=20)),
                ('genres', models.CharField(blank=True, max_length=2000)),
                ('homepage', models.CharField(blank=True, max_length=200)),
                ('idd', models.CharField(blank=True, max_length=20)),
                ('imdb_id', models.CharField(blank=True, max_length=200)),
                ('original_language', models.CharField(blank=True, max_length=20)),
                ('original_title', models.CharField(blank=True, max_length=200)),
                ('overview', models.CharField(blank=True, max_length=2000)),
                ('popularity', models.CharField(blank=True, max_length=200)),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('production_companies', models.CharField(blank=True, max_length=1000)),
                ('production_countries', models.CharField(blank=True, max_length=1000)),
                ('release_date', models.CharField(blank=True, max_length=200)),
                ('revenue', models.CharField(blank=True, max_length=20)),
                ('runtime', models.CharField(blank=True, max_length=20)),
                ('spoken_languages', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=2000)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video', models.CharField(blank=True, max_length=20)),
                ('vote_average', models.CharField(blank=True, max_length=20)),
                ('vote_count', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
