# Generated by Django 2.1.4 on 2020-04-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movi', '0003_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=20)),
                ('movieId', models.CharField(blank=True, max_length=20)),
                ('rating', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
